# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import pablo_pb2 as pablo__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in pablo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BankingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MakePayment = channel.unary_unary(
                '/protocol.Banking/MakePayment',
                request_serializer=pablo__pb2.TransactionInit.SerializeToString,
                response_deserializer=pablo__pb2.Status.FromString,
                _registered_method=True)
        self.UpdateBalance = channel.unary_unary(
                '/protocol.Banking/UpdateBalance',
                request_serializer=pablo__pb2.TrxInfo.SerializeToString,
                response_deserializer=pablo__pb2.Status.FromString,
                _registered_method=True)
        self.CreditMoney = channel.unary_unary(
                '/protocol.Banking/CreditMoney',
                request_serializer=pablo__pb2.Credit.SerializeToString,
                response_deserializer=pablo__pb2.Status.FromString,
                _registered_method=True)
        self.CheckBalance = channel.unary_unary(
                '/protocol.Banking/CheckBalance',
                request_serializer=pablo__pb2.Status.SerializeToString,
                response_deserializer=pablo__pb2.Credit.FromString,
                _registered_method=True)
        self.Registration = channel.unary_unary(
                '/protocol.Banking/Registration',
                request_serializer=pablo__pb2.Register.SerializeToString,
                response_deserializer=pablo__pb2.Status.FromString,
                _registered_method=True)
        self.PrepareTransaction = channel.unary_unary(
                '/protocol.Banking/PrepareTransaction',
                request_serializer=pablo__pb2.PrepareRequest.SerializeToString,
                response_deserializer=pablo__pb2.PrepareResponse.FromString,
                _registered_method=True)
        self.CommitTransaction = channel.unary_unary(
                '/protocol.Banking/CommitTransaction',
                request_serializer=pablo__pb2.CommitRequest.SerializeToString,
                response_deserializer=pablo__pb2.Status.FromString,
                _registered_method=True)
        self.Pinger = channel.unary_unary(
                '/protocol.Banking/Pinger',
                request_serializer=pablo__pb2.Ping.SerializeToString,
                response_deserializer=pablo__pb2.Ping.FromString,
                _registered_method=True)


class BankingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MakePayment(self, request, context):
        """Sender to Gateway
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBalance(self, request, context):
        """Gateway to Banks (both debiting and crediting)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreditMoney(self, request, context):
        """Sent by Receiver client to Gateway server.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckBalance(self, request, context):
        """Client asks for its balance from gateway, the same message is
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Registration(self, request, context):
        """sent by gateway to bank server to get balance.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrepareTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Pinger(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BankingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MakePayment': grpc.unary_unary_rpc_method_handler(
                    servicer.MakePayment,
                    request_deserializer=pablo__pb2.TransactionInit.FromString,
                    response_serializer=pablo__pb2.Status.SerializeToString,
            ),
            'UpdateBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBalance,
                    request_deserializer=pablo__pb2.TrxInfo.FromString,
                    response_serializer=pablo__pb2.Status.SerializeToString,
            ),
            'CreditMoney': grpc.unary_unary_rpc_method_handler(
                    servicer.CreditMoney,
                    request_deserializer=pablo__pb2.Credit.FromString,
                    response_serializer=pablo__pb2.Status.SerializeToString,
            ),
            'CheckBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckBalance,
                    request_deserializer=pablo__pb2.Status.FromString,
                    response_serializer=pablo__pb2.Credit.SerializeToString,
            ),
            'Registration': grpc.unary_unary_rpc_method_handler(
                    servicer.Registration,
                    request_deserializer=pablo__pb2.Register.FromString,
                    response_serializer=pablo__pb2.Status.SerializeToString,
            ),
            'PrepareTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareTransaction,
                    request_deserializer=pablo__pb2.PrepareRequest.FromString,
                    response_serializer=pablo__pb2.PrepareResponse.SerializeToString,
            ),
            'CommitTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitTransaction,
                    request_deserializer=pablo__pb2.CommitRequest.FromString,
                    response_serializer=pablo__pb2.Status.SerializeToString,
            ),
            'Pinger': grpc.unary_unary_rpc_method_handler(
                    servicer.Pinger,
                    request_deserializer=pablo__pb2.Ping.FromString,
                    response_serializer=pablo__pb2.Ping.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protocol.Banking', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('protocol.Banking', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Banking(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MakePayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protocol.Banking/MakePayment',
            pablo__pb2.TransactionInit.SerializeToString,
            pablo__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protocol.Banking/UpdateBalance',
            pablo__pb2.TrxInfo.SerializeToString,
            pablo__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreditMoney(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protocol.Banking/CreditMoney',
            pablo__pb2.Credit.SerializeToString,
            pablo__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protocol.Banking/CheckBalance',
            pablo__pb2.Status.SerializeToString,
            pablo__pb2.Credit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Registration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protocol.Banking/Registration',
            pablo__pb2.Register.SerializeToString,
            pablo__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PrepareTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protocol.Banking/PrepareTransaction',
            pablo__pb2.PrepareRequest.SerializeToString,
            pablo__pb2.PrepareResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protocol.Banking/CommitTransaction',
            pablo__pb2.CommitRequest.SerializeToString,
            pablo__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Pinger(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protocol.Banking/Pinger',
            pablo__pb2.Ping.SerializeToString,
            pablo__pb2.Ping.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
